SXDefault-1:
  Name: '&b雷霆领主项链'
  ID: 287
  Lore:
  - '&6物品类型: 项链'
  - '&c生命上限: +200'
  - '&d移速增幅: +50%'
  - '&d雷霆几率: +20%'
  - '&6限制等级: <r:20_30>级'
  - '&r'
  - '&e出售价格: 500'
  - '&r'
  - '&8&o拥有着驾驭飞行的能力'
  - '&8&o"放在背包第三行最后一格生效"'
  EnchantList:
  - DURABILITY:1
SXDefault-2:
  Name: '&c&l鸽子肉'
  ID: '351:7'
  Lore:
  - ''
  - '&6物品类型: 宝藏'
  - ''
  - '&b连肉都散发出了耀眼光芒'
  - ''
  - '&8&o"放在背包第一行最后一格生效"'
  EnchantList:
  - DURABILITY:1
  ItemFlagList:
  - HIDE_ENCHANTS
